name: BingoTests
version: '${project.version}'
main: bingotests.bingotests.BingoTests
api-version: 1.19
authors: [ dvarlan ]
description: A test Plugin for Minecraft Bingo
website: https://github.com/dvarlan
commands:
  top:
    description: Teleports the player back to the surface or the overworld if in the nether
  team:
    description: Lets the user manipulate / interact with teams
  bingoboard:
    description: Command for showing and randomly filling the bingoboard
  bingo:
    description: Checks if the player / team obtained all items & ends the game